// <auto-generated />
using System;
using MCloudServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCloudServer.Migrations
{
    [DbContext(typeof(DbCtx))]
    [Migration("20221229041601_user_store")]
    partial class user_store
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("MCloudServer.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("tag")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("tag");

                    b.HasIndex("uid");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("MCloudServer.ConfigItem", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("MCloudServer.LoginRecord", b =>
                {
                    b.Property<string>("token")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("last_used")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("login_date")
                        .HasColumnType("TEXT");

                    b.HasKey("token");

                    b.HasIndex("UserId");

                    b.ToTable("logins", (string)null);
                });

            modelBuilder.Entity("MCloudServer.PlayRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("audioprofile")
                        .HasColumnType("TEXT");

                    b.Property<int>("listid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.Property<int>("trackid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("audioprofile");

                    b.HasIndex("listid");

                    b.HasIndex("time");

                    b.HasIndex("trackid");

                    b.HasIndex("uid");

                    b.ToTable("plays", (string)null);
                });

            modelBuilder.Entity("MCloudServer.StoredFile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.Property<long>("size")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("file");
                });

            modelBuilder.Entity("MCloudServer.Track", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("album")
                        .HasColumnType("TEXT");

                    b.Property<string>("albumArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("artist")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ctime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("fileRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("groupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lyrics")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("owner")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("pictureFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("thumbPictureFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("fileRecordId");

                    b.HasIndex("owner");

                    b.HasIndex("pictureFileId");

                    b.HasIndex("thumbPictureFileId");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("MCloudServer.TrackAudioInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Peaks")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("trackAudioInfo");
                });

            modelBuilder.Entity("MCloudServer.TrackFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConvName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileID");

                    b.HasIndex("TrackID");

                    b.ToTable("trackFile");
                });

            modelBuilder.Entity("MCloudServer.TrackList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("owner")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("picId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("trackids")
                        .HasColumnType("TEXT");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int>("visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("owner");

                    b.HasIndex("picId");

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("MCloudServer.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("avatarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("last_playing")
                        .HasColumnType("TEXT");

                    b.Property<string>("lists")
                        .HasColumnType("TEXT");

                    b.Property<string>("passwd")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.Property<int>("version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("avatarId");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MCloudServer.UserSocialLink", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("accessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("idFromProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("nameFromProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("refreshToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.HasIndex("provider", "idFromProvider")
                        .IsUnique();

                    b.ToTable("userSocialLinks");
                });

            modelBuilder.Entity("MCloudServer.UserStoreItem", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("key")
                        .HasColumnType("TEXT");

                    b.Property<int>("revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("value")
                        .HasColumnType("BLOB");

                    b.Property<int>("visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("userId", "key");

                    b.ToTable("userStore", (string)null);
                });

            modelBuilder.Entity("MCloudServer.Comment", b =>
                {
                    b.HasOne("MCloudServer.User", "user")
                        .WithMany()
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("MCloudServer.LoginRecord", b =>
                {
                    b.HasOne("MCloudServer.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCloudServer.PlayRecord", b =>
                {
                    b.HasOne("MCloudServer.Track", "Track")
                        .WithMany()
                        .HasForeignKey("trackid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCloudServer.User", "User")
                        .WithMany()
                        .HasForeignKey("uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCloudServer.Track", b =>
                {
                    b.HasOne("MCloudServer.StoredFile", "fileRecord")
                        .WithMany()
                        .HasForeignKey("fileRecordId");

                    b.HasOne("MCloudServer.User", "user")
                        .WithMany()
                        .HasForeignKey("owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCloudServer.StoredFile", "pictureFile")
                        .WithMany()
                        .HasForeignKey("pictureFileId");

                    b.HasOne("MCloudServer.StoredFile", "thumbPictureFile")
                        .WithMany()
                        .HasForeignKey("thumbPictureFileId");

                    b.Navigation("fileRecord");

                    b.Navigation("pictureFile");

                    b.Navigation("thumbPictureFile");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MCloudServer.TrackAudioInfo", b =>
                {
                    b.HasOne("MCloudServer.Track", "Track")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MCloudServer.TrackFile", b =>
                {
                    b.HasOne("MCloudServer.StoredFile", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCloudServer.Track", "Track")
                        .WithMany("files")
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MCloudServer.TrackList", b =>
                {
                    b.HasOne("MCloudServer.User", "user")
                        .WithMany()
                        .HasForeignKey("owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCloudServer.StoredFile", "pic")
                        .WithMany()
                        .HasForeignKey("picId");

                    b.Navigation("pic");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MCloudServer.User", b =>
                {
                    b.HasOne("MCloudServer.StoredFile", "avatar")
                        .WithMany()
                        .HasForeignKey("avatarId");

                    b.Navigation("avatar");
                });

            modelBuilder.Entity("MCloudServer.UserSocialLink", b =>
                {
                    b.HasOne("MCloudServer.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("MCloudServer.Track", b =>
                {
                    b.Navigation("files");
                });
#pragma warning restore 612, 618
        }
    }
}
