name: Docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (master, latest)
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yuuza/musiccloud:latest
      -
        name: Build and push (dev)
        if: github.ref_name == 'dev'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yuuza/musiccloud:dev

  # docker-arm64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: true
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         platforms: linux/arm64
  #         push: true
  #         tags: yuuza/musiccloud:latest
